# Generated by Django 5.1.1 on 2024-09-19 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Destination Loction')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Destination Description')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_time', models.DateTimeField()),
                ('return_time', models.DateTimeField()),
                ('dress_code', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=35000, null=True)),
                ('departure_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_picture', models.ImageField(blank=True, null=True, upload_to='destination_pics/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])])),
                ('price_include', models.CharField(blank=True, choices=[('Accommondatio', 'Accommondatio'), ('Porter & Personal Guide', 'Porter & Personal Guide'), (' Insurance', ' Insurance'), ('Breakfast', 'Breakfast'), (' Tranportation / Car', ' Tranportation / Car')], max_length=50, null=True)),
            ],
        ),
    ]
