# Generated by Django 5.1.1 on 2024-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Destination Location'),
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price_include',
        ),
        migrations.AddField(
            model_name='destination',
            name='price_include',
            field=models.ManyToManyField(blank=True, to='destination.priceadvantage'),
        ),
    ]
